/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
export const indexTemplateHtml = `<div><div :class="tocClass" ref="toc"><tree :data="toc" :preid="preid" @toggle="toggle($event)" @change="change($event)"></tree></div><div :class="contentClass" v-html="content" ref="content"></div><div :class="navClass" @click="toggleNavigation()">{{ isNavExpand ? "«" : "»"}}</div></div>`;
