// @ts-nocheck
/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
import { createElementBlock as _createElementBlock, createElementVNode as _createElementVNode, createVNode as _createVNode, normalizeClass as _normalizeClass, openBlock as _openBlock, resolveComponent as _resolveComponent, toDisplayString as _toDisplayString } from 'vue'
// tslint:disable
/* eslint-disable */

export function indexTemplateHtml(_ctx, _cache) {
  const _component_tree = _resolveComponent("tree")

  return (_openBlock(), _createElementBlock("div", null, [
    _createElementVNode("div", {
      class: _normalizeClass(_ctx.tocClass),
      ref: "toc"
    }, [
      _createVNode(_component_tree, {
        data: _ctx.toc,
        preid: _ctx.preid,
        onToggle: _cache[0] || (_cache[0] = $event => (_ctx.toggle($event))),
        onChange: _cache[1] || (_cache[1] = $event => (_ctx.change($event)))
      }, null, 8 /* PROPS */, ["data", "preid"])
    ], 2 /* CLASS */),
    _createElementVNode("div", {
      class: _normalizeClass(_ctx.contentClass),
      innerHTML: _ctx.content,
      ref: "content"
    }, null, 10 /* CLASS, PROPS */, ["innerHTML"]),
    _createElementVNode("div", {
      class: _normalizeClass(_ctx.navClass),
      onClick: _cache[2] || (_cache[2] = $event => (_ctx.toggleNavigation()))
    }, _toDisplayString(_ctx.isNavExpand ? "«" : "»"), 3 /* TEXT, CLASS */)
  ]))
}
/* eslint-enable */
// tslint:enable
