// @ts-nocheck
/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
/* eslint-disable */
import { App } from "./index"

export function indexTemplateHtml(this: App) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',[_c('div',{ref:"toc",class:_vm.tocClass},[_c('tree',{attrs:{"data":_vm.toc,"preid":_vm.preid},on:{"toggle":function($event){return _vm.toggle($event)},"change":function($event){return _vm.change($event)}}})],1),_vm._v(" "),_c('div',{ref:"content",class:_vm.contentClass,domProps:{"innerHTML":_vm._s(_vm.content)}}),_vm._v(" "),_c('div',{class:_vm.navClass,on:{"click":function($event){return _vm.toggleNavigation()}}},[_vm._v(_vm._s(_vm.isNavExpand ? "«" : "»"))])])}
export var indexTemplateHtmlStatic = [  ]
/* eslint-enable */
// tslint:enable
